### ISSUE TITLE
Excessão SQL ao Registar utilizador

### ISSUE THREAD

**Issue by sineiro** [TiagoRodrigues95/Projecto_ESW_1920#1]
<h1>Problema</h1>

![image](https://user-images.githubusercontent.com/10634173/71447481-b957c900-2726-11ea-93ea-b24289e57702.png)

<h3>Descrição</h3>
Não se consegue efetuar o registo de um utilizador, independentemente de existir uma conta ou não na base de dados.

<h3>Reprodução da excessão</h3>

- Seleciono o link "Registar";
- Preencho o formulário com os dados válidos e conta não registada;
- Submeto formulário;
- Exceção SQL;

<h3>Funcionalidades afetadas</h3>

- Registar;
- Login;
- Todas as funcionalidade do sistema que necessitam de acesso à base de dados;

<h3>Tentativas de Resolução</h3>

- Tentativa 1: [erro] - Pressionar botão "Apply Migrations" na página em que aparece o erro;
- Tentativa 2: [sem sucesso] - Realizar update-database;
- Tentativa 3: [sem sucesso] - Realizar add-migration e depois update-database;

**Comment by TiagoRodrigues95** [comment]
tentar remover as migrations do projecto e criar novas
se nao resultar corta o projecto todo excepto as migrations e depois cria um projecto novo à parte, cola tudo nesse projecto e coloca esse projecto no nosso, efectuato o apply migration <migration name> e depois o update-database. 
Feliz natal

**Comment by sineiro** [comment]
Resolvido
