### ISSUE TITLE
Revisão de documentação no código

### ISSUE THREAD

**Issue by sineiro** [TiagoRodrigues95/Projecto_ESW_1920#3]
<h1>Problema</h1>
<h3>Descrição</h3>
Reparei que existem algumas discrepâncias de como estamos a declarar as classes, controladores, atributos e até mesmo variáveis.

Por essa mesma razão quero discutir neste tópico para nos organizar melhor no que toca a código.

O que foi definido no nosso documento foi a utilização do CamelCase, mas pelo que vejo talvez necessitamos de esclarecer melhor o assunto.

<h3>Normas de codificação (Provisório)</h3>

- Nome das classe : CamelCase (e.g. Utilizador, InqueritoResposta);
- Nome dos atributos : CamelCase (e.g. Nome, ProtocoloUrl);
- Nome dos atributos Primary Key: NomeClasseId (e.g. UtilizadorId);
- Nome dos atributos Foreign Key: NomeClasse_Id (e.g. EmpresaId);

**Comment by sineiro** [comment]
Deixo no issue,  a forma que segui com a norma CamelCase e a utilização de definição de atributos PK e FK.
Comentem para se for necessário sofrer alterações para entrarmos no caminho certo.

**Comment by TiagoRodrigues95** [comment]
nao podemos usar nas Foreign Key isto "NomeClasse_Id" pois o vs nao utiliza coneccçoes dessa maneira
como podemos fazer é qe quando tem PK tem [Required] e NotNull enquando é FK nao a tem

**Comment by sineiro** [comment]
Alterei "Nome dos atributos Foreign Key: NomeClasse_Id (e.g. Empresa_Id);" para "Nome dos atributos Foreign Key: NomeClasse_Id (e.g. EmpresaId);".

**Comment by sineiro** [comment]
Fecharei este issue por considerar "resolvido".
