### ISSUE TITLE
Erro de migrações PFC.  "Introducing FOREIGN KEY constraint 'FK_PFC_AspNetUsers_DocenteId' on table 'PFC' may cause cycles or multiple cascade paths"

### ISSUE THREAD

**Issue by sineiro** [TiagoRodrigues95/Projecto_ESW_1920#7]
<h1>Problema</h1>

![image](https://user-images.githubusercontent.com/10634173/71847948-2aec2b80-30c6-11ea-8e68-4371c2f71f85.png)

![image](https://user-images.githubusercontent.com/10634173/71847928-1dcf3c80-30c6-11ea-93a4-356308ded136.png)

<h3>Descrição</h3>
Ao adicionar as migrações do add_pfc_2 através do comando update-database, o erro, acima ilustrado, ocorre.

<h3>Reprodução do erro</h3>
- Fazer update-database;

<h3>Funcionalidades afetadas</h3>
- Migrações futuras.

**Comment by TiagoRodrigues95** [comment]
![image](https://user-images.githubusercontent.com/43936037/72000624-9c99b600-323b-11ea-9d27-3d1bbaa5d4e6.png)

![image](https://user-images.githubusercontent.com/43936037/72000640-a3282d80-323b-11ea-9155-7b1efa307d4e.png)

na marcarçao de duvidas existe este erro ao fazer update-database
na consola 
eu preciso qe isto esteja resolvido ate amanha

**Comment by sineiro** [comment]
Já se consegue fazer update-database sem erros.
Resolvido.
